# Generated by Django 3.2.22 on 2023-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
