# Generated by Django 3.2.22 on 2023-11-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blog_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blogs.png', upload_to='blogs'),
        ),
    ]
